name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.11'
  GO_VERSION: '1.21'

jobs:
  # Lint and Test Ingestion Service
  test-ingestion:
    name: Test Ingestion Service
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: services/ingestion/package-lock.json

      - name: Install dependencies
        working-directory: ./services/ingestion
        run: npm ci

      - name: Run linter
        working-directory: ./services/ingestion
        run: npm run lint || echo "Linting not configured yet"

      - name: Run type check
        working-directory: ./services/ingestion
        run: npm run type-check || npx tsc --noEmit

      - name: Run tests
        working-directory: ./services/ingestion
        run: npm test || echo "Tests not configured yet"

      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v3
        with:
          files: ./services/ingestion/coverage/lcov.info
          flags: ingestion
          name: ingestion-coverage

  # Lint and Test Normalisation Service
  test-normalisation:
    name: Test Normalisation Service
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: services/normalisation/requirements.txt

      - name: Install dependencies
        working-directory: ./services/normalisation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov black flake8 mypy

      - name: Run Black formatter check
        working-directory: ./services/normalisation
        run: black --check src/ || echo "Black check not configured yet"

      - name: Run Flake8 linter
        working-directory: ./services/normalisation
        run: flake8 src/ --max-line-length=100 || echo "Flake8 not configured yet"

      - name: Run type checking
        working-directory: ./services/normalisation
        run: mypy src/ || echo "MyPy not configured yet"

      - name: Run tests
        working-directory: ./services/normalisation
        run: pytest --cov=src --cov-report=xml || echo "Tests not configured yet"

      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v3
        with:
          files: ./services/normalisation/coverage.xml
          flags: normalisation
          name: normalisation-coverage

  # Integration Tests
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [test-ingestion, test-normalisation]
    
    services:
      nats:
        image: nats:2.10-alpine
        ports:
          - 4222:4222
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:8222/healthz || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: postgis/postgis:16-3.4-alpine
        env:
          POSTGRES_DB: omnitrack_test
          POSTGRES_USER: omnitrack
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U omnitrack"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mongodb:
        image: mongo:7
        env:
          MONGO_INITDB_ROOT_USERNAME: omnitrack
          MONGO_INITDB_ROOT_PASSWORD: test_pass
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Ingestion Service dependencies
        working-directory: ./services/ingestion
        run: npm ci

      - name: Install Normalisation Service dependencies
        working-directory: ./services/normalisation
        run: pip install -r requirements.txt

      - name: Initialize test database
        run: |
          PGPASSWORD=test_pass psql -h localhost -U omnitrack -d omnitrack_test -c "CREATE EXTENSION IF NOT EXISTS postgis;"
          PGPASSWORD=test_pass psql -h localhost -U omnitrack -d omnitrack_test -f scripts/init-schema.sql || echo "Schema init skipped"

      - name: Start Ingestion Service
        working-directory: ./services/ingestion
        env:
          NODE_ENV: test
          PORT: 3000
          NATS_URL: nats://localhost:4222
          MONGODB_URL: mongodb://omnitrack:test_pass@localhost:27017
          API_KEY: test_api_key
        run: |
          npm start &
          echo $! > ingestion.pid
          sleep 5

      - name: Start Normalisation Service
        working-directory: ./services/normalisation
        env:
          ENVIRONMENT: test
          NATS_URL: nats://localhost:4222
          REDIS_URL: redis://localhost:6379
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: omnitrack_test
          POSTGRES_USER: omnitrack
          POSTGRES_PASSWORD: test_pass
        run: |
          python -m src.main &
          echo $! > normalisation.pid
          sleep 5

      - name: Run E2E tests
        run: |
          chmod +x scripts/test-e2e.sh
          ./scripts/test-e2e.sh || echo "E2E tests not fully configured yet"

      - name: Stop services
        if: always()
        run: |
          [ -f services/ingestion/ingestion.pid ] && kill $(cat services/ingestion/ingestion.pid) || true
          [ -f services/normalisation/normalisation.pid ] && kill $(cat services/normalisation/normalisation.pid) || true

  # Code Quality Checks
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true

      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  # Dependency Security Scan
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: NPM Audit (Ingestion)
        working-directory: ./services/ingestion
        run: npm audit --audit-level=moderate || true

      - name: Python Safety Check (Normalisation)
        working-directory: ./services/normalisation
        run: |
          pip install safety
          safety check || true

  # Build Status Summary
  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [test-ingestion, test-normalisation, integration-tests, code-quality, security-scan]
    if: always()
    
    steps:
      - name: Check build status
        run: |
          echo "Build Summary:"
          echo "- Ingestion Tests: ${{ needs.test-ingestion.result }}"
          echo "- Normalisation Tests: ${{ needs.test-normalisation.result }}"
          echo "- Integration Tests: ${{ needs.integration-tests.result }}"
          echo "- Code Quality: ${{ needs.code-quality.result }}"
          echo "- Security Scan: ${{ needs.security-scan.result }}"
